// Generated by CoffeeScript 1.6.3
(function() {
  var FormView, view, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FormView = (function(_super) {
    __extends(FormView, _super);

    function FormView() {
      this.rememberChange = __bind(this.rememberChange, this);
      this.labelClick = __bind(this.labelClick, this);
      this.submit = __bind(this.submit, this);
      _ref = FormView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    FormView.prototype.el = "#login-form";

    FormView.prototype.ui = {
      items: ".form-item",
      labels: "label",
      inputs: "input",
      username: "input[name=username]",
      password: "input[type=password]",
      remember: "[data-bind=remember]",
      submit: "button[type=submit]",
      button: {
        forgot: {
          username: "[data-action=forgot-username]",
          password: "[data-action=forgot-password]"
        }
      }
    };

    FormView.prototype.events = {
      "submit": "submit",
      "click button.forgot.username": "forgotUsername",
      "click button.forgot.password": "forgotPassword",
      "click labels": "labelClick",
      "change remember": "rememberChange"
    };

    FormView.prototype.initialize = function() {
      this.ui.username.val("user");
      this.ui.password.val("secret!");
      return this.ui.remember.attr("checked", true);
    };

    FormView.prototype.render = function() {
      return this.ui.username.focus();
    };

    FormView.prototype.submit = function(e) {
      return e.preventDefault();
    };

    FormView.prototype.forgotUsername = function() {
      alert("An email with your username has been sent.");
      return false;
    };

    FormView.prototype.forgotPassword = function() {
      alert("An email with your password in plain text has been sent. Trust us, we're professionals.");
      return false;
    };

    FormView.prototype.labelClick = function(e) {
      var el, label;
      label = $(e.target);
      el = this.ui[label.attr("for")];
      return el.focus();
    };

    FormView.prototype.rememberChange = function(e) {
      return console.log("remember field changed");
    };

    return FormView;

  })(Backbone.View);

  view = new FormView();

  view.render();

}).call(this);
